config/routes.rb
Mappo2::Application.routes.draw do
  
  devise_for  :users,
              :controllers => { :registrations => "custom_devise/registrations"}

  root to: 'pages#home'
  match '/index', to: 'pages#index'
  match '/home', to: 'pages#home'
  match '/help', to: 'pages#help'

  match '/datasets/:id/locations', to: 'datasets#locations_of', :as => :locations_of
  match '/datasets/:id/map', to: 'datasets#dataset_map', :as => :dataset_map
  match '/datasets/:id/timeline', to: 'datasets#timeline', :as => :timeline
  match '/datasets/:id/geochart_region', to: 'datasets#geochart_region', :as => :geochart_region
  match '/datasets/:id/geochart_markers', to: 'datasets#geochart_markers', :as => :geochart_markers
  match '/datasets/:id/map/embed/embedmap', to: 'datasets#embedmap', :as => :embedmap
  match '/datasets/:id/timeline/embed/embedtimeline1', to: 'datasets#embedtimeline1', :as => :embedtimeline1
  match '/datasets/:id/timeline/embed/embedtimeline2', to: 'datasets#embedtimeline2', :as => :embedtimeline2

  resources :works, :except => :index do
    collection { post :import }
  end

  resources :locations, :except => [:index, :destroy]

  resources :datasets, :except => :index

end

app/models/dataset.rb
# == Schema Information
#
# Table name: datasets
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  works_id    :integer
#  user_id     :integer
#

class Dataset < ActiveRecord::Base
  include Obfuscate
  attr_accessible :description, :title
  attr_accessible :works, :work_attributes, :work_ids, :user_id

  belongs_to :work
  has_many :works
  has_many :locations, :through => :works 
  accepts_nested_attributes_for :works
  belongs_to :user

  def to_param
    encrypt id
  end

  #def self.find(id)
    #id=decrypt id
    #super
  #end


  def auto_marker_icon(current_user)
  	hexcolor=select_color(current_user)
  	first = title.split('').first.upcase
  	# chld = letter(s) written in the marker | marker's hex color | letter(s) color
  	"http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld="+first+"|"+hexcolor+"|"
  end

  def select_color(current_user)
  	# 		red 		blue 	yellow 		orange 	lightblue	green	purple		brown	white	gray
  	colors=["FF0000", "0000ff", "ffff00", "ffa500", "add8e6", "00ff00", "a020f0", "a52a2a", "fff", "bebebe"]
  	num=0
  	ids=current_user.dataset_ids
  	ids.each do |usr_id|
  		if usr_id == id
  			break
  		else
  			num+=1
  		end
  	end
  	if num > colors.length
  		num=0
  	end
  	colors[num]
  end
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_filter :get_globals_for_single_ds, :except => [:index, :new, :create, :destroy]
  before_filter :open_dataset, :only => [:show, :edit, :update, :locations_of, :dataset_map, :timeline, :geochart_region, :geochart_markers, :embedmap, :embedtimeline1, :embedtimeline2]
  before_filter :map, :only => [:show, :dataset_map]
  before_filter :authenticate_user!, :except => [:embedmap, :embedtimeline1, :embedtimeline2]
  before_filter :user_datasets
  before_filter :check_user, :only => [:show, :edit, :locations_of, :dataset_map, :timeline, :geochart_markers, :geochart_region]

  def check_user
    unless current_user.datasets.include? @dataset
      redirect_to root_path
    end
  end
  # GET /datasets
  # GET /datasets.json
  def index
    @datasets = Dataset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @datasets }
    end
  end

  # GET /datasets/1
  # GET /datasets/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dataset }
    end
  end

  # GET /datasets/new
  # GET /datasets/new.json
  def new
    @dataset = Dataset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dataset }
    end
  end

  # GET /datasets/1/edit
  def edit
  end

  # POST /datasets
  # POST /datasets.json
  def create
    @dataset = Dataset.new(params[:dataset])
    current_user.datasets << @dataset

    respond_to do |format|
      if @dataset.save
        format.html { redirect_to @dataset, notice: 'Dataset was successfully created.' }
        format.json { render json: @dataset, status: :created, location: @dataset }
      else
        format.html { render action: "new" }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /datasets/1
  # PUT /datasets/1.json
  def update
    respond_to do |format|
      if @dataset.update_attributes(params[:dataset])
        format.html { redirect_to @dataset, notice: 'Dataset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datasets/1
  # DELETE /datasets/1.json
  def destroy
    @dataset = Dataset.find(Dataset.decrypt(params[:id]))
    @dataset.works.each do |w|
      Work.check_n_destroy_locations(w)
      w.destroy
    end
    @dataset.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  #embed
  def embedmap
    map
    render :layout => false
  end

  def embedtimeline1
    @chart1 = prepare_timeline
    render :layout => false
  end

  def embedtimeline2
    @chart2 = prepare_timeline_inline
    render :layout => false
  end
  
  #pagine
  def locations_of
    @pie_chart = pie_chart
    @region_chart = geo_chart_region_mode
  end

  def dataset_map
  end

  def timeline
    @chart1 = prepare_timeline
    @chart2 = prepare_timeline_inline
  end

  def geochart_region
    @region_chart = geo_chart_region_mode
  end

  def geochart_markers
    @marker_chart = geo_chart_marker_mode
    @marker_chart.add_listener("regionClick", "function(e) {
      opts={region: e['region'], displayMode: 'markers', width: 800, colorAxis: {colors: ['#FF8747', '#FFB581', '#c06000']}, enableRegionInteractivity: true};
      chart.draw(data_table, opts)}")
    @marker_chart.add_listener( 
      "select", 
      "function(e) {
      var selection = chart.getSelection();
      if(typeof selection[0] !== 'undefined') {
        var selected = data_table.getValue(selection[0].row, 0); 
        var arr = selected.split(', ');
        var country = isoCodes[arr[arr.length-1].toUpperCase()];
        options={region: country, displayMode: 'markers', width: 800, colorAxis: {colors: ['#FF8747', '#FFB581', '#c06000']}, enableRegionInteractivity: true};
        chart.draw(data_table, options)
      }
      }")
  end

  def length_for_timeline(works)
    cont=0
    works.each do |work|
      if work.start && work.end
        cont+=1
      end
    end
    cont
  end

  #visualizzazioni
  def prepare_timeline
    data_table = GoogleVisualr::DataTable.new

    data_table.new_column('string', t('name'))
    data_table.new_column('string', 'Label')
    data_table.new_column('date', t('start'))
    data_table.new_column('date', t('end'))

    @works.each do |work|
      data_table.add_row([work.name.to_s, work.name.to_s, work.start.to_date, work.end.to_date]) if work.start && work.end && work.name
    end  
    heightpx = (length_for_timeline(@works) * 41)+50
    options = { :height => heightpx, :timeline => {singleColor: '#0080ff'} }
    GoogleVisualr::Interactive::Timeline.new(data_table, options)
  end

  def prepare_timeline_inline
    data_table = GoogleVisualr::DataTable.new
    
    data_table.new_column('string', t('name'))
    data_table.new_column('string', 'Label')
    data_table.new_column('date', t('start'))
    data_table.new_column('date', t('end'))

    @works.each do |work|
      data_table.add_row([" ", work.name.to_s, work.start.to_date, work.end.to_date]) if work.start && work.end && work.name
    end
    options={}
    GoogleVisualr::Interactive::Timeline.new(data_table, options)
  end

  def pie_chart
    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('string', t('country'))
    data_table.new_column('number', t('projects'))
    
    get_countries.each do |country|
      data_table.add_row([country.to_s, get_works_in_country(country)])
    end
    opts   = { :width => 400, :height => 300, :title => t('projects_per_country'), :is3D => true }
    GoogleVisualr::Interactive::PieChart.new(data_table, opts)
  end

  def geo_chart_region_mode
    data_table_regions = GoogleVisualr::DataTable.new
    data_table_regions.new_column('string'  , t('country')   )
    data_table_regions.new_column('number'  , t('projects')  )
    
    get_countries.each do |country|
      data_table_regions.add_row([country.to_s, get_works_in_country(country)])
    end

    opts   = { :displayMode => 'regions', :width => 800 }
    GoogleVisualr::Interactive::GeoChart.new(data_table_regions, opts) 
  end
  def one_country(locations)
    countries=[]
    locations.each do |loc|
      countries << loc.country
    end
    countries.uniq.length==1
  end
  def geo_chart_marker_mode
    data_table_markers = GoogleVisualr::DataTable.new
    data_table_markers.new_column('string', t('name'))
    data_table_markers.new_column('number', t('projects'))

    @locations.each do |loc|
      data_table_markers.add_row([loc.get_name, loc.get_works_length_in_ds(current_dataset) ])
    end
    opts={ :displayMode => 'markers', :colorAxis => {:colors => ['#FF8747', '#FFB581', '#c06000']}, :width => 800, enableRegionInteractivity: true}
    if one_country(@locations)
      if Country.find_country_by_name(@locations.first.country)  #no match -> nil
        opts={ :region => Country.find_country_by_name(@locations.first.country).alpha2,:displayMode => 'markers', :colors => ['#FF8747', '#FFB581', '#c06000'], :width => 800, enableRegionInteractivity: true}
      end 
    end
    GoogleVisualr::Interactive::GeoChart.new(data_table_markers, opts)
  end

  def map
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      if location.latitude!=nil && location.longitude!=nil 
        marker.lat location.latitude 
        marker.lng location.longitude
        marker.infowindow render_to_string(:partial => "/locations/infowindow", :locals => { :location => location })
      end
    end
    @hash.delete_if{|elem| elem.blank?} if @hash
  end
  #utilizzo per le altre funzioni
  def get_countries
    countries=[]
    @locations.each do |loc|
      countries << loc.country.capitalize if loc.country
    end
    countries.uniq
  end

  def get_works_in_country(country)
    cont=0
    @locations.each do |loc|
      if loc.country
        cont+=loc.get_works_length_in_ds(@dataset) if loc.country.capitalize == country
      end
    end
    cont
  end

  def get_globals_for_single_ds
    @dataset = Dataset.find(Dataset.decrypt(params[:id]))
    @works = @dataset.works.sort_by {|obj| obj.name}
    @locations = @dataset.locations.find(:all, :order => :name).uniq
  end

  def user_datasets
    @datasets = current_user.datasets if current_user
  end

  def open_dataset
    session[:current_dataset_id]=@dataset.id
    current_dataset
  end
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/views/datasets/_form.html.erb
<%= form_for(@dataset) do |f| %>
  <% if @dataset.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@dataset.errors.count, "error") %> prohibited this dataset from being saved:</h2>

      <ul>
      <% @dataset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= t('title')%>:  <%= f.text_field :title %></p>
  </div>
  <div class="field">
    <p><%= t('description')%>:  <%= f.text_area :description %></p>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/datasets/_map.html.erb
<div class="map" id="map" style='width: 100%; height: 100%;'></div>

<script type="text/javascript">
	$(document).ready(function(){
		showMap(<%=raw @hash.to_json %>);
	})
</script>

app/views/datasets/dataset_map.html.erb
<h1>Mappa</h1>
<div style="width:900px; height:400px;">
	<%= render 'map' %>
</div>
<br>
<div align="right" style="width:900px;">
<button class="btn embed-button"><%= t 'embed_map'%></button>
</div>
<div class="embed hidden bubble" style="width: 500px;">
	<p><%= t 'embed_map'%></p>
	<input id="width_iframe_map" placeholder=<%= t 'width'%> style="width: 50px">
	<input id="height_iframe_map" placeholder=<%= t 'height'%> style="width: 50px;">
	<br><br><button class="btn btn-primary generate"><%= t 'generate'%></button>
	<br><br><input class="hidden" id="embed-code" style="width: 100%;">
</div>


<script type="text/javascript">
$(document).ready(function(){
	$('.embed-button').click(function(){
		$('.embed-button').hide();
		$('.embed').show();
	});
	$('.generate').click(function(){
		$iframe=generate_map_iframe()
		$('#embed-code').val($iframe);
		$('#embed-code').show();
	});
})
</script>

app/views/datasets/edit.html.erb
<h1><%= t('edit_dataset')%></h1>

<%= render 'form' %>

<%= link_to t('show'), @dataset %> |
<%= link_to t('back'), :back %>

app/views/datasets/embedmap.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header'%>
<body>
	<div class="map" id="map" style="width:100%; height:100%"></div>
	<script type="text/javascript">
	$(document).ready(function(){
		showMap(<%=raw @hash.to_json %>);
	})
	</script>
</body>
</html>

app/views/datasets/embedtimeline1.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header'%>
<body>
	<div id="timeline1"></div>
	<%= render_chart(@chart1, 'timeline1') %>
</body>
</html>

app/views/datasets/embedtimeline2.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header'%>
<body>
	<div id="timeline2"></div>
	<%= render_chart(@chart2, 'timeline2') %>
</body>
</html>

app/views/datasets/geochart_markers.html.erb
<h1><%= t 'projects_per_area' %></h1>
<p><%= t 'can_click' %></p>

<div id='marker_chart' style="width: 800px;"></div>
<%= render_chart @marker_chart, 'marker_chart' %>

app/views/datasets/geochart_region.html.erb
<h1><%= t 'density_per_country'%></h1>
<div id='region_chart' style="width: 800px;"></div>
<%= render_chart @region_chart, 'region_chart' %>

app/views/datasets/index.html.erb
<h1>Listing datasets</h1>

<%= render 'datasets/datasets_index'%>

app/views/datasets/locations_of.html.erb
<h1><%= t('locations_in') + @dataset.title%></h1>
<br>
<div id='region_chart' style="width: 800px;"></div>
<br>
<div class="container-fluid" style="width: 800px;">
	<div class="span5">
		<div id='pie'></div>
	</div>
	<div class="span2">
		<%= render "/locations/locations_index"%>
	</div>
</div>

<%= render_chart @pie_chart, 'pie' %>
<%= render_chart @region_chart, 'region_chart' %>

app/views/datasets/new.html.erb
<h1><%= t('new_dataset')%></h1>

<%= render 'form' %>

<%= link_to t('back'), home_path %>

app/views/datasets/show.html.erb
<%if notice%>
<div class="alert alert-success" role="alert">
  <p id="notice"><%= notice %></p>
</div>
<%end%>
<div>
  <h2><%= @dataset.title %></h2>
  <div class="map" id="map" style='width: 95%; height: 400px;'></div>
  <br><br>
  <div class="container-fluid" align="center">
    <div class="span" style="width: 60%; text-align:left;  margin:5px;">
      <div class="bubble">
        <p>
          <b><%= t 'description'%>:</b>
          <p><%= @dataset.description %></p>
        </p>
        <p><b><%= t 'n_projects'%>:</b> <%=@works.length%></p>
        <div style="text-align:right;">
          <%= link_to t('add_project').html_safe, new_work_path, class: "btn" %>
        </div>
      </div>
      <br>
      <div class="bubble">
        <%= render 'works/works_index'%>
      </div>
    </div><!-- span6 -->
    <div class="span" style="width: 30%;">
      <div class="import bubble">
        <b><%= t 'upload_info'%></b>
        <%= form_tag import_works_path, multipart: true do %>
        <p><%= t 'import_attributes'%></p>
        <%= hidden_field_tag :dataset_id, @dataset.id%>
        <%= text_field_tag :project_id, nil,placeholder: "Project ID" %>
        <%= text_field_tag :name, nil,placeholder: "Name" %>
        <%= text_field_tag :places, nil,placeholder: "Places" %>
        <%= text_field_tag :start, nil,placeholder: "Start" %>
        <%= text_field_tag :end, nil,placeholder: "End" %>
        <%= file_field_tag :file %>
        <%= submit_tag  t('upload'), class: 'btn btn-primary' %>
        <% end %>
        <p><%= t 'upload_help'%> <%= link_to t('help_section'), help_path%></p>
      </div><!-- import -->
      <br>
    </div><!-- span5 -->
  </div><!-- cont-fluid-->
  <br>
  
  <br><br>
  <%= link_to t('edit'), edit_dataset_path(@dataset), :class => "btn" %> |
  <%= link_to t('delete'), @dataset, method: :delete, data: { confirm: t('sure') }, :class => "btn btn-danger"  %>
</div>

<script type="text/javascript">
$(document).ready(function(){
  showMap(<%=raw @hash.to_json %>);
})
</script>

app/views/datasets/timeline.html.erb
<div style="width: 900px;">
	<h1>Timeline</h1>
	<div id="timeline1"></div>
	<%= render_chart(@chart1, 'timeline1') %>
	<div align="right">
		<button class="btn embed-button-tl1"><%= t 'embed_timeline'%>1</button>
	</div>
	<div class="embed-tl1 hidden bubble" style="width: 50%;">
		<p><%= t 'embed_timeline'%>1</p>
		<input id="width_iframe_tl1" placeholder=<%= t 'width'%> style="width: 50px">
		<input id="height_iframe_tl1" placeholder=<%= t 'height'%> style="width: 50px;">
		<br><br><button class="btn btn-primary generate-tl1"><%= t 'generate'%></button>
		<br><br><input class="hidden" id="embed-code-tl1" style="width: 100%;">
	</div>
	<br>
	<h3 style="text-align: left;"><%= t 'inline'%>:</h3>
	<div id="timeline2"></div>
	<%= render_chart(@chart2, 'timeline2') %>
	<div align="right">
		<button class="btn embed-button-tl2"><%= t 'embed_timeline'%>2</button>
	</div>
	<div class="embed-tl2 hidden bubble" style="width: 50%;">
		<p><%= t 'embed_timeline'%>2</p>
		<input id="width_iframe_tl2" placeholder=<%= t 'width'%> style="width: 50px">
		<input id="height_iframe_tl2" placeholder=<%= t 'height'%> style="width: 50px;">
		<br><br><button class="btn btn-primary generate-tl2"><%= t 'generate'%></button>
		<br><br><input class="hidden" id="embed-code-tl2" style="width: 100%;">
	</div>
	<br><br>
	<div class="bubble">
		<%= render "works/works_index" %>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('.embed-button-tl1').click(function(){
		$('.embed-button-tl1').hide();
		$('.embed-tl1').show();
	});
	$('.generate-tl1').click(function(){
		$iframe=generate_tl1_iframe()
		$('#embed-code-tl1').val($iframe);
		$('#embed-code-tl1').show();
	});
	$('.embed-button-tl2').click(function(){
		$('.embed-button-tl2').hide();
		$('.embed-tl2').show();
	});
	$('.generate-tl2').click(function(){
		$iframe=generate_tl2_iframe()
		$('#embed-code-tl2').val($iframe);
		$('#embed-code-tl2').show();
	});
})
</script>