config/routes.rb
Mappo2::Application.routes.draw do
  
  devise_for  :users,
              :controllers => { :registrations => "custom_devise/registrations"}

  root to: 'pages#home'
  match '/index', to: 'pages#index'
  match '/home', to: 'pages#home'
  match '/help', to: 'pages#help'

  match '/datasets/:id/locations', to: 'datasets#locations_of', :as => :locations_of
  match '/datasets/:id/map', to: 'datasets#dataset_map', :as => :dataset_map
  match '/datasets/:id/timeline', to: 'datasets#timeline', :as => :timeline
  match '/datasets/:id/geochart_region', to: 'datasets#geochart_region', :as => :geochart_region
  match '/datasets/:id/geochart_markers', to: 'datasets#geochart_markers', :as => :geochart_markers
  match '/datasets/:id/map/embed/embedmap', to: 'datasets#embedmap', :as => :embedmap
  match '/datasets/:id/timeline/embed/embedtimeline1', to: 'datasets#embedtimeline1', :as => :embedtimeline1
  match '/datasets/:id/timeline/embed/embedtimeline2', to: 'datasets#embedtimeline2', :as => :embedtimeline2

  resources :works, :except => :index do
    collection { post :import }
  end

  resources :locations, :except => [:index, :destroy]

  resources :datasets, :except => :index

end

app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  project_id :string(255)
#  start      :date
#  end        :date
#  places     :text
#  extra      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  dataset_id :integer
#

class Work < ActiveRecord::Base
  attr_accessible :end, :extra, :name, :places, :project_id, :start
  attr_accessible :locations, :location_ids, :location_attributes
  attr_accessible :dataset, :dataset_id, :dataset_attribute
  attr_accessor :extra_keys, :extra_values

  serialize :extra, Hash #the extra field is 'text' in the database but i want it as a hash
  belongs_to :dataset
  has_one :dataset
  has_many :location_works
  has_many :locations, :through => :location_works
  accepts_nested_attributes_for :locations

  validates :name, :presence => true

  def self.get_array_attr #usato in import qui sotto
    array_attr=[]
    accessible_attributes.each do |attr|
      array_attr.push attr.to_s if attr!=""
    end
    array_attr
  end

  def self.customize_header(header, custom_attrs)
    if custom_attrs["project_id"] && header.include?(custom_attrs["project_id"]) && custom_attrs["project_id"]!="project_id"
      header[header.index custom_attrs["project id"]] = "project_id"
    end
    if custom_attrs["name"] && header.include?(custom_attrs["name"]) && custom_attrs["name"]!="name"
      header[header.index custom_attrs["name"]] = "name"
    end
    if custom_attrs["places"] && header.include?(custom_attrs["places"]) && custom_attrs["places"]!="places"
      header[header.index custom_attrs["places"]] = "places"
    end
    if custom_attrs["start"] && header.include?(custom_attrs["start"]) && custom_attrs["start"]!="start"
      header[header.index custom_attrs["start"]] = "start"
    end
    if custom_attrs["end"] && header.include?(custom_attrs["end"]) && custom_attrs["end"]!="end"
      header[header.index custom_attrs["end"]] = "end"
    end
    header
  end

  def self.import(file, custom_attrs)
    spreadsheet = open_spreadsheet(file)
    spreadsheet.row(1).each do |column|
      column.downcase!
    end
    header = spreadsheet.row(1)
    if header.include? "project id"
      header[header.index "project id"] = "project_id" 
    end
    spreadsheet_header=header
    header=customize_header header, custom_attrs
    (2..spreadsheet.last_row).each do |i|
      hash = Hash[[header, spreadsheet.row(i)].transpose]
      if header.include?("project_id") && !hash["project_id"].blank?
        work = find_by_project_id_and_dataset_id(hash["project_id"], custom_attrs["dataset_id"]) || new
      else
        work = find_by_name_and_dataset_id(hash["name"], custom_attrs["dataset_id"]) || new
      end
      work.attributes = hash.to_hash.slice(*accessible_attributes)
      #attributi che non fanno parte del modello vengono salvati nella hash 'extra'
      keys=header - get_array_attr
      values=[]
      keys.each do |elem|
        values << hash[elem]
      end
      if hash["extra"]
        keys << "extra"
        values << hash["extra"]
      end
      work.extra = Hash[[keys, values].transpose]

      Dataset.find(custom_attrs["dataset_id"]).works << work
      work.save!
      Work.create_locations(work) if work.places
      Location.destroy_unused
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.ods' then Roo::OpenOffice.new(file.path, file_warning: :ignore) 
    when '.csv' then Roo::CSV.new(file.path, file_warning: :ignore)
    when '.xls' then Roo::Excel.new(file.path, file_warning: :ignore)
    when '.xlsx' then Roo::Excelx.new(file.path, file_warning: :ignore)
    else raise "File type not supported: #{file.original_filename}"
    end
  end

  private 

  def self.create_locations(work)
    work.locations.clear
    arrayplaces=CSV.parse_line work.places.gsub ", ", "," #funziona solo senza spazi tra le virgole
    unless arrayplaces
      return
    end
    arrayplaces.each do |a|
      arrloc=Geocoder.search a
      #arrloc è un array di oggetti del geocoder, punterei sul first per trovare country e coords
      unless arrloc.blank?
        country=arrloc.first.country
        lat=arrloc.first.latitude
        lng=arrloc.first.longitude
        Work.save_location(work, a, country, lat, lng)
      else
        Work.save_location(work, a, nil, nil, nil)
      end
    end#arrayplaces each
  end

  def self.check_diff_name_location(loc, name, country, lat, lng)
    if !Location.find_by_name_and_country(name, country) && Location.find_by_latitude_and_longitude(lat, lng)
    #in questo caso ci sono due posti con name diverso ma stesse coordinate.. 
    #cerco di tenere il nome abbastanza generico, tipo la città se c'è o se no il nome usato nell'address
    georesults=Geocoder.search [lat, lng]
    unless georesults.blank?
      if georesults.first.city
        loc.name=georesults.first.city
      else 
        if georesults.first.data["address_components"].first["long_name"]
          loc.name=georesults.first.data["address_components"].first["long_name"]
        else
            loc.name=Work.capitalize_names(name) #se non trovo quegli altri nomi devo sovrascrivere
          end
        end
      end
    else
      loc.name=Work.capitalize_names(name)
    end
  end

  def self.save_location(work, name, country, lat, lng)
    loc = Location.find_by_name_and_country(name, country) || Location.find_by_latitude_and_longitude(lat, lng) || Location.new
    loc.name=Work.capitalize_names(name)
    loc.country=country
    loc.latitude=lat
    loc.longitude=lng
    work.locations << loc if !(work.locations.include? loc) #la aggiungo se non è già nella lista
    loc.save!
  end

  def self.capitalize_names(name)
    if name
      arr=name.split " "
      arr.each do |n|
        n.capitalize!
      end
      arr.join " "
    end
  end

  def self.check_n_destroy_locations(work)
    work.locations.each do |location|
      if location.works.length==1 #hanno solo il work che sto distruggendo
        location.destroy
      end
    end
  end

  def self.remove_location_from(work, loc)
    if work.locations.include? loc
      work.locations.delete loc
      if loc.works.length==1
        loc.destroy
      end
    end
  end

  def self.rewrite_all_places_from_locations
    Work.all.each do |work|
      if work.places && work.locations
        #if work.places.include?(")") || work.places.include?(";")
        work.places=""
        work.locations.sort.each do |loc|
          work.places << loc.name
          unless loc==work.locations.sort.last
            work.places << "," 
          end
        end
      work.save
        #end
      end
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_filter :get_work, :only => [:show, :edit, :update, :destroy, :open_dataset]
  before_filter :open_dataset, :only => [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :user_datasets
  before_filter :check_user, :only => [:show, :edit, :destroy]

  def check_user
    unless current_user.datasets.include? Dataset.find(@work.dataset_id)
      redirect_to root_path
    end
  end
  # GET /works
  # GET /works.json
  def index
    @works = Work.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @locations=@work.locations
    map
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/new
  # GET /works/new.json
  def new
    @work = Work.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(params[:work].except(:extra_keys, :extra_values))
    @work.extra = process_extra if params[:extra_keys]
    
    current_dataset.works << @work
    
    Work.create_locations(@work) if @work.places

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render json: @work, status: :created, location: @work }
      else
        format.html { render action: "new" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /works/1
  # PUT /works/1.json
  def update
    @work.extra = process_extra if params[:work][:extra_keys] && params[:work][:extra_keys]!= ""
    respond_to do |format|
      if @work.update_attributes(params[:work].except(:extra_keys, :extra_values))
        Work.create_locations(@work) if @work.places#.changed?
        Location.destroy_unused
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    #controllare che le location che lascia non siano vuote
    Work.check_n_destroy_locations(@work)
    @work.destroy

    respond_to do |format|
      format.html { redirect_to url_for current_dataset }
      format.json { head :no_content }
    end
  end

  def remove_location(wid, lid)
    work=Work.find(wid)
    loc=Location.find(lid)
    Work.remove_location_from(work,loc)
  end

  def get_work
    @work = Work.find(params[:id])
  end

  def open_dataset
    session[:current_dataset_id]=@work.dataset_id
    current_dataset
  end

  def import
    attributes={"dataset_id"=>params[:dataset_id],"project_id"=>params[:project_id],"name"=>params[:name],"places"=>params[:places],"start"=>params[:start],"end"=>params[:end]}
    attributes.values.each do |attribute|
      attribute.downcase! if attribute
    end
    if params[:file] && params[:dataset_id]
      Work.import(params[:file], attributes)
    end
    redirect_to dataset_path(Dataset.find(params[:dataset_id])), notice: "File successfully uploaded."
  end

  def process_extra
    params[:work][:extra_keys].delete! "\n"
    params[:work][:extra_keys].delete! "\r"
    params[:work][:extra_values].delete! "\r"
    params[:work][:extra_values].delete! "\n"

    keys=JSON.parse(params[:work][:extra_keys])
    values=JSON.parse(params[:work][:extra_values])
    
    params[:work].delete :extra_keys
    params[:work].delete :extra_values
    

    for i in 0...keys.length
      if keys[i]==""
        keys.delete_at(i)
        values.delete_at(i)
      end
    end
    
    Hash[[keys, values].transpose]
  end

  def map
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      if location.latitude!=nil && location.longitude!=nil 
        marker.lat location.latitude 
        marker.lng location.longitude
        marker.infowindow render_to_string(:partial => "/locations/infowindow", :locals => { :location => location })
      end
    end
    @hash.delete_if{|elem| elem.blank?} if @hash
  end

  def user_datasets
    @datasets = current_user.datasets if current_user
  end
end #workscontroller

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
<% if @work.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

  <ul>
    <% @work.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="name-field">
  <p><%= t 'name'%>:  <%= f.text_field :name %></p>
</div>
<div class="name-field">
  <p><%= t 'project_id'%>:  <%= f.text_field :project_id %></p>
</div>
<div class="start-field">
<p><%= t 'start_ext'%>:   <%= f.text_field :start, :class => 'datepicker'%></p>
</div>
<div class="end-field">
  <p><%= t 'end_ext'%>:   <%= f.text_field :end, :class => 'datepicker'%></p>
</div>
<div class="places-field">
  <%= f.label :places, "Places" %>
  <%= f.hidden_field :places, :id => :places %>
  <textarea id="loc" class="hidden"><%=""+@work.locations.to_json%></textarea>
</div>
<div class="extra-hidden-field">
  <%= f.hidden_field :extra_keys, :id => :extra_keys %>
  <%= f.hidden_field :extra_values, :id => :extra_values %>
</div>
<div class="places-text-fields"></div>
<div class="btn" id="add-place-field"><%= t('add_locations').html_safe%></div><br><br>
<div class="extra-text-fields">
  <p><%= t 'extra_fields'%></p>
  <% if @work.extra %>
    <% cont=0 %>
    <% @work.extra.each do |key, value| %>
      <input id=<%= 'extra-in-'+cont.to_s%> type="text" value= <%=""+key.to_s%>>
      <textarea id=<%= 'extra-tx-'+cont.to_s%>  type="text"><%=value.to_s%></textarea>
      <br>
      <% cont+=1 %>
    <% end #each%>
    <input id="cont_for_extra_update" type="hidden" value= <%=""+@work.extra.length.to_s%>>
  <%end #if%>
</div>
<div class="btn" id="add-extra-field"><%= t('add_field').html_safe%></div><br /><br />
<div class="btn btn-primary" id="process-data"><%= t('finish') %></div><br /><br />
<div class="actions hidden">
  <%= f.submit :class => "submit" %>
</div>
<% end %>


<script type="text/javascript">
//le funzioni usate sono in app/assets/javascripts/works.js
var cont_inputs_extra=0;
var cont_inputs_place=0;

$(document).ready(function(){
    cont=$('#cont_for_extra_update').val();
    if (cont && cont!=""){
      cont_inputs_extra=parseInt(cont);
      //voglio sapere quanti campi ci sono già in extra così poi so quanti ne vanno in process_extra, perché i valori nei vari campi vengono uniti per essere mandati al controller
    }
    //mette le informazioni già presenti du places nei campi dell'update
    places=$('#places').val();
    if (places && places!=""){ 
      cont_inputs_place=prepare_places_for_update();
    }

    $('#add-extra-field').click(function(){
      addextrafield(cont_inputs_extra);
      cont_inputs_extra++;
    });

    $('#add-place-field').click(function(){
      addplaces(cont_inputs_place);
      cont_inputs_place++;
    });

    //formatta i vari campi in più e li mette in extra pronti per il controller
    $('#process-data').click(function(){
      process_extra(cont_inputs_extra);
      process_places(cont_inputs_place);
      $('.submit').trigger("click");
    });
  });
</script>

app/views/works/_works_index.html.erb
<table class="table">
  <tr>
    <th><%= t 'name'%></th>
    <th><%= t 'project_id'%></th>
    <th><%= t 'n_locations'%></th>
    <th><%= t 'start'%></th>
    <th><%= t 'end'%></th>
    <th><%= t 'edit' %></th>
    <th><%= t 'delete' %></th>
  </tr>

<% @works.sort.each do |work| %>
  <tr>
    <td><%= link_to work.name, work %></td>
    <td><%= work.project_id %></td>
    <td><%= work.locations.length %></td>
    <td><%= work.start %></td>
    <td><%= work.end %></td>
    <td><%= link_to '<i class="fa fa-pencil fa-fw"></i>'.html_safe, edit_work_path(work) %></td>
    <td><%= link_to '<i class="fa fa-trash fa-fw"></i>'.html_safe, work, method: :delete, data: { confirm: t('sure') } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('new_project'), new_work_path, class: "btn" %>

app/views/works/edit.html.erb
<h1><%= t('edit_project')%></h1>

<%= render 'form' %>

<%= link_to t('show'), @work %> |
<%= link_to t('back'), :back %>

app/views/works/index.html.erb
<h1>Listing works</h1>

<%= render 'works_index'%>

app/views/works/new.html.erb
<h1><%= t('new_project')%></h1>

<%= render 'form' %>

<%= link_to t('back'), :back %>

app/views/works/show.html.erb
<%if notice%>
<div class="alert alert-success" role="alert">
  <p id="notice"><%= notice %></p>
</div>
<%end%>
<h2 align="center"><%= @work.name %></h2>
<div class="bubble" style="width: 80%; text-align:left;">
  <div align="center"> 
    <div class="map" id="map" style='width: 80%; height: 300px;'></div>
  </div>
  <div style="width:80%; margin-left: auto; margin-right:auto;">
    <p>
      <b><%= t('project_id')%>:</b>
      <%= @work.project_id %>
    </p>
    <p>
      <b><%= t('start_ext')%>:</b>
      <%= @work.start.strftime("%d/%m/%Y") if @work.start %>
    </p>
    <p>
      <b><%= t('end_ext')%>:</b>
      <%= @work.end.strftime("%d/%m/%Y") if @work.end %>
    </p>
    <div>
        <%keys=@work.extra.keys
        hash=@work.extra%>
        <%if !keys.blank?%>
        <% keys.each do |key| %>
        <p>
          <b><%= key.capitalize if key%>: </b>
          <%= hash[key] %>
        </p>
        <% end %>
        <%end%>
      </div>
    <div>
      <p><b>Luoghi:</b>(<%=@work.locations.length%>)</p>
    </div>
    <%= render "/locations/locations_index"%>
  </div>
</div>
<br>
<%= link_to t('edit'), edit_work_path(@work), :class => "btn" %> |
<%= link_to t('delete'), @work, method: :delete, data: { confirm: t('sure') }, :class => "btn btn-danger"  %>

<script type="text/javascript">
$(document).ready(function(){
  showMap(<%=raw @hash.to_json %>);
})
</script>