config/routes.rb
Mappo2::Application.routes.draw do
  
  devise_for  :users,
              :controllers => { :registrations => "custom_devise/registrations"}

  root to: 'pages#home'
  match '/index', to: 'pages#index'
  match '/home', to: 'pages#home'
  match '/help', to: 'pages#help'

  match '/datasets/:id/locations', to: 'datasets#locations_of', :as => :locations_of
  match '/datasets/:id/map', to: 'datasets#dataset_map', :as => :dataset_map
  match '/datasets/:id/timeline', to: 'datasets#timeline', :as => :timeline
  match '/datasets/:id/geochart_region', to: 'datasets#geochart_region', :as => :geochart_region
  match '/datasets/:id/geochart_markers', to: 'datasets#geochart_markers', :as => :geochart_markers
  match '/datasets/:id/map/embed/embedmap', to: 'datasets#embedmap', :as => :embedmap
  match '/datasets/:id/timeline/embed/embedtimeline1', to: 'datasets#embedtimeline1', :as => :embedtimeline1
  match '/datasets/:id/timeline/embed/embedtimeline2', to: 'datasets#embedtimeline2', :as => :embedtimeline2

  resources :works, :except => :index do
    collection { post :import }
  end

  resources :locations, :except => [:index, :destroy]

  resources :datasets, :except => :index

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  country    :string(255)
#  latitude   :float
#  longitude  :float
#  gmaps      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ActiveRecord::Base
	geocoded_by :gmaps4rails_address
	after_validation :geocode, if: ->(obj){ obj.name_changed? or obj.country_changed? }

	attr_accessible :country, :latitude, :longitude, :name, :gmaps
	attr_accessible :works, :works_attributes

	has_many :location_works
	has_many :works, :through => :location_works

	#validates :country, :presence => true

	def get_name
		if name && name!="" && name!=" " && name!=country
			return "#{name}, #{country}"
		end
		return "#{country}"
	end

	def manual_geocode
		if !name.blank?
			arraygeoc=Geocoder.search name
		else
			if !country.blank?
				arraygeoc=Geocoder.search country
			else
				return false
			end
		end
		
		if arraygeoc.blank?
			return false
		end
		geocoded=arraygeoc.first
		latitude=geocoded.latitude
		longitude=geocoded.longitude
		save!
		return true
	end

	def is_geocoded?
		return latitude && longitude && latitude!="" && longitude!=""
	end

	def is_geocoded_html?
		if latitude && longitude && latitude!="" && longitude!=""
			return	'<i class="fa fa-check found"></i>'.html_safe
		end
		return '<i class="fa fa-close not-found"></i>'.html_safe
	end

	def gmaps4rails_address
		[name, country].compact.join(', ')
	end

	def get_works_length_in_ds(openDS)
		cont=0
		works.each do |work|
			cont += 1 if work.dataset_id == openDS.id
		end
		cont
	end
	def works_in_ds(openDS)
		ret = []
		works.each do |work|
			ret << work if work.dataset_id == openDS.id
		end
		ret
	end
	def get_dataset_ids(usr)
		dataset_ids=[]
		works.each do |work|
			ds=Dataset.find_by_id(work.dataset_id)
			if ds && ds.user == usr
				dataset_ids << work.dataset_id
			end
		end
		dataset_ids.uniq
	end

	def self.destroy_unused
		Location.all.each do |loc|
      		if loc.works.length==0
        		loc.destroy
      		end
    	end
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :user_datasets
  before_filter :current_dataset
  # GET /locations
  # GET /locations.json
  def check_user
    unless current_user.locations.include? @location
      redirect_to root_path
    end
  end
  def index
    @locations = Location.find(:all, :order => :name)    
    check_locations(@locations)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
    check_user
    @hash = Gmaps4rails.build_markers(@location) do |location, marker|
      if location.latitude!=nil && location.longitude!=nil 
        marker.lat location.latitude
        marker.lng location.longitude
        marker.infowindow render_to_string(:partial => "/locations/infowindow", :locals => { :location => location })
      end
    end
    @hash.delete_if{|elem| elem.blank?} if @hash

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end
  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
    check_user
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])
    Location.destroy_unused
    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    #non c'è più la route per questo
    #le locations vengono rimosse dai progetti modificando i progetti
    #se viene tolta una location viene fatto un controllo e si cancellano le locations non utilizzate
    @location = Location.find(params[:id])
    check_user
    @location.destroy
    Location.destroy_unused #ne approfitto per fare un po' di pulizia se serve

    respond_to do |format|
      format.html { redirect_to url_for current_dataset }
      format.json { head :no_content }
    end
  end

  def user_datasets
    @datasets = current_user.datasets if current_user
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= t 'name'%>:  <%= f.text_field :name %></p>
  </div>
  <div class="field">
    <p><%= t 'country'%>:  <%= f.text_field :country %></p>
  </div>
  <div class="field">
    <p><%= t 'latitude'%>:  <%= f.text_field :latitude %></p>
  </div>
  <div class="field">
    <p><%= t 'longitude'%>:  <%= f.text_field :longitude %></p>
  </div>
  <div class="actions">
 <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/locations/_home_infowindow.html.erb
<div class="infowindow" align="center">
	<h4> <%= location.get_name%> </h4>
	<p><%=t('list')+ "(#{location.works.uniq.length}):"%></p>
	
	<%location.get_dataset_ids(current_user).each do |did|%>
	<div class="infobubble">
		<b><%=Dataset.find(did).title%></b>
		<ul>
			<%location.works.each do |work|%>
			<%if work.dataset_id == did%>
			<li><%= work.name %></li>
			<%end%>
			<% end %>
		</ul>
	</div>
	<%end%>
</div>

app/views/locations/_infowindow.html.erb
<div class="infowindow" align="center">
	<h4> <%= location.get_name %> </h4>
	 <%if @current_dataset%>
	 <p><%= t('list')+ "(#{location.get_works_length_in_ds(@current_dataset)}):"%></p>
	<div class="infobubble">
		<ul>
		<%location.works_in_ds(@current_dataset).each do |work|%>
		<li><%= work.name %></li>
		<% end %>
		</ul>
	</div>
	<%end%>
</div>

app/views/locations/_locations_index.html.erb
<table class="table">
  <tr>
    <th></th>
    <th><%= t 'name'%></th>
    <th><%= t 'country'%></th>
    <th><%= t 'found'%></th>
    <th><%= t 'edit' %></th>
  </tr>
  <% @locations.sort.each do |location| %>
  <tr>
    <td><%= link_to '<i class="fa fa-arrow-right fa-fw"></i>'.html_safe, location %></td>
    <td><%= location.name %></td>
    <td><%= location.country %></td>
    <td><%= location.is_geocoded_html?%></td>
    <td><%= link_to '<i class="fa fa-pencil fa-fw"></i>'.html_safe, edit_location_path(location) %></td>
  </tr>
  <% end %>
</table>

app/views/locations/edit.html.erb
<h1><%= t 'edit_location'%></h1>

<%= render 'form' %>

<%= link_to t('show'), @location %> |
<%= link_to t('back'), :back %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<%= render 'locations_index' %>

app/views/locations/new.html.erb
<h1><%= t 'new_location'%></h1>

<%= render 'form' %>

<%= link_to t('back'), :back %>

app/views/locations/show.html.erb
<%if notice%>
<div class="alert alert-success" role="alert">
  <p id="notice"><%= notice %></p>
</div>
<%end%>
<h2>
  <%= 
  if @location.name && @location.name!=""
    "#{@location.name}, #{@location.country}"
  else
    "#{@location.country}"
  end
  %>
</h2>
<div class="bubble" style="width:80%; text-align:left;">
  <div align="center"> 
    <div class="map" id="map" style='width: 80%; height: 300px;'></div>
  </div>
  <div style="width:80%; margin-left: auto; margin-right:auto;">
    <p>
      <b><%= t('latitude')%>:</b>
      <%= @location.latitude %>
    </p>
    <p>
      <b><%= t('longitude')%>:</b>
      <%= @location.longitude %>
    </p>
    <p>
      <b<%= t('projects_in_place')%>:</b>
    </p>
    <%if @current_dataset%>
    <p>
      <% @location.works_in_ds(@current_dataset).each do |work| %>
      <p><%= link_to work.name, work %>
      <%= ", " if work!=@location.works_in_ds(@current_dataset).last %></p>
      <%end%>
    </p>
    <%end%>
  </div>
</div>
<br><br>
<%= link_to t('edit'), edit_location_path(@location), :class => "btn" %>

<script type="text/javascript">
$(document).ready(function(){
  showMap(<%=raw @hash.to_json %>);
})
</script>