config/routes.rb
Mappo2::Application.routes.draw do
  
  devise_for  :users,
              :controllers => { :registrations => "custom_devise/registrations"}

  root to: 'pages#home'
  match '/index', to: 'pages#index'
  match '/home', to: 'pages#home'
  match '/help', to: 'pages#help'

  match '/datasets/:id/locations', to: 'datasets#locations_of', :as => :locations_of
  match '/datasets/:id/map', to: 'datasets#dataset_map', :as => :dataset_map
  match '/datasets/:id/timeline', to: 'datasets#timeline', :as => :timeline
  match '/datasets/:id/geochart_region', to: 'datasets#geochart_region', :as => :geochart_region
  match '/datasets/:id/geochart_markers', to: 'datasets#geochart_markers', :as => :geochart_markers
  match '/datasets/:id/map/embed/embedmap', to: 'datasets#embedmap', :as => :embedmap
  match '/datasets/:id/timeline/embed/embedtimeline1', to: 'datasets#embedtimeline1', :as => :embedtimeline1
  match '/datasets/:id/timeline/embed/embedtimeline2', to: 'datasets#embedtimeline2', :as => :embedtimeline2

  resources :works, :except => :index do
    collection { post :import }
  end

  resources :locations, :except => [:index, :destroy]

  resources :datasets, :except => :index

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <ul>
      <li></li>
    </ul>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("help"),  help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<head>
	<title>Mappo2</title>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
	<%= csrf_meta_tags %>
</head>

app/views/layouts/_navbar.html.erb
<nav class="navbar" style="margin-bottom: 5px;">
	<div class="navbar-inner">
		<div class="container">
			<ul class="nav pull-right">
				<%=render 'layouts/usernavigation'%>
			</ul>
			<ul class="nav pull-left">
				<li><%=link_to '<i class="fa fa-home fa-fw"></i>Home'.html_safe, home_path%></li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_navbar2.html.erb
<% if @current_dataset %>
<ul class="nav-tabs nav" align="center" style="width: 100%; height:50px;">
	<li><%= link_to @current_dataset.title, @current_dataset%></li>
	<li><%= link_to t('locations'),locations_of_path(@current_dataset)%></li>
	<li><%= link_to t('map'), dataset_map_path(@current_dataset)%></li>
	<li><%= link_to "Geochart", geochart_region_path(@current_dataset)%></li>
	<li><%= link_to "Marker Chart", geochart_markers_path(@current_dataset)%></li>
	<li><%= link_to "Timeline", timeline_path(@current_dataset)%></li>
</ul>
<% end %>

app/views/layouts/_usernavigation.html.erb
<% if user_signed_in? %>
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    <i class="fa fa-user fa-fw"></i><%= current_user.name%>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><%= link_to t('edit_account').html_safe, edit_user_registration_path %></li>
    <li role="presentation"><%= link_to '<i class="fa fa-sign-out fa-fw"></i>Logout'.html_safe, destroy_user_session_path, :method=>'delete' %></li>
  </ul>
</div>
<% else %>
<li>
  <%= link_to 'Login', new_user_session_path %>
</li>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header'%>
<body>
	<div class='body'>
		<%= render 'layouts/navbar'%>
		<%if current_user && @datasets %>
		<div class="container-fluid" style="padding:0;">
			<div class="span sidemenu">
				<%= render 'pages/sidebar' %>
			</div><!-- span2 -->
			<div class="main2" align="center">
				<%= render 'layouts/navbar2'%>
				<%= yield %>
				<br /><br /><br /><br /><br />
			</div><!-- main-->
		</div><!--contfluid-->
		<%else%>
		<div class="main" align="center">
			<%= render 'layouts/navbar2'%>
			<%= yield %>
			<br /><br /><br /><br /><br />
		</div><!-- main-->
		<%end%>
	</div>
	<%= render 'layouts/footer'%>
</body>
</html>